### ISSUE TITLE
persistent_toggle buggy in Firefox

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_personal_facts#1]
apparently as soon as there is more than one Checkbox?

Checkbox state is sometimes not displayed corrently, data toggle is also affected.
Works ok in Chrome.

See also
https://stackoverflow.com/questions/29484632/firefox-click-and-change-events-on-checkbox-elements-which-are-not-appended-int
https://stackoverflow.com/questions/14463971/jquery-click-checkbox-doesnt-check-in-firefox

**Comment by Gunnar-GO** [comment]
i had the same behavior with chrome, but think jquery wasn't load fully at the moment of test.

**Comment by ric2016** [comment]
I cannot reproduce this with Firefox 72 and the current webtrees version. It has hopefully been resolved by now.
