### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_personal_facts#25]
It seems that a translation is missing.

<img width="490" alt="Bildschirmfoto 2021-01-07 um 19 17 17" src="https://user-images.githubusercontent.com/16311627/103929378-8740bb80-511d-11eb-8b65-d056203ac883.png">

**Comment by ric2016** [comment]
Many German translations are missing. As in webtrees itself, they may be contributed via weblate. This string in particular is used in multiple modules, and therefore to be translated in ['Vesta Common'](https://hosted.weblate.org/translate/vesta-webtrees-custom-modules/vesta-common/de/?q=associated).

**Comment by mpwt** [comment]
Thank you for the link to the weblate platform you used. 

Why was the labelling changed for webtrees v2?
webtrees v1.7: Facts and events of inverse associates - Ereignisse von invers assoziierten Personen
webtrees v2.0: Associated facts and events

Not that the previous labelling or translation were perfect, but the labelling referred to inversely associated persons and not only to their events. The new one is not necessarily easier to understand for visitors.

**Comment by ric2016** [comment]
I agree - I just haven't been able to come up with a better term for this (one that is both concide and easy to understand). The current term was suggested by another user.

Perhaps I should add a '?' icon explaining it?

**Comment by mpwt** [comment]
Events of associates - Ereignisse von verbundenen Personen ?

I use it only for the facts and events tab ...
