### ISSUE TITLE
Add Mapservice for Europe in the XIX. century

### ISSUE THREAD

**Issue by Gunnar-GO** [vesta-webtrees-2-custom-modules/vesta_personal_facts#3]
Hi, 

wouldn't it be nice to see old maps in addition to the linked actual ones ?
In that way areas that not existing anymore would be also seeable.

For example

http://gov.genealogy.net/item/show/KALFENKO04DV

would result:
https://mapire.eu/en/map/europe-19century-secondsurvey/?bbox=2252576.40660626,7340941.971594488,2258591.0452694497,7343808.360155182&map-list=0&layers=158,164

and without a menu 

https://mapire.eu/en/map/europe-19century-secondsurvey/embed/?bbox=2252576.40660626,7340941.971594488,2258591.0452694497,7343808.360155182&map-list=0&layers=158,164

acutally i'm not sure in which way the points are connected with the long/lat. but since it is automatically used in http://data.matricula-online.eu/ it should be able to generate.

Just as idea, if i find more information to make it possible, i will add this here.

**Comment by ric2016** [comment]
I have just released a new version with this feature.
Not sure if we should restrict the link to facts and events places of the respective time, for now the link appears everywhere (if configured).

Thank you for the suggestion, this is indeed a nice feature to have!

**Comment by Gunnar-GO** [comment]
nice , thx :)
