### ISSUE TITLE
Use of Translation for "Witness at a marriage"

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_personal_facts#31]
Hallo, diesmal habe ich hoffentlich ausreichend lange darüber nachgedacht ... Als begeisterter Nutzer der Anzeige von „Ereignissen verbundener Personen“ fiel mir jetzt in der aktuellen Version auf, dass die Übersetzung für RELA "witness“ bei einer Trauung/Hochzeit unabhängig vom Geschlecht der bezeugenden Person immer mit "Trauzeugin bei einer Hochzeit" angezeigt wird.

![49323D87-3971-435A-AF82-7F6117731617](https://user-images.githubusercontent.com/16311627/106625165-b577b680-6576-11eb-85d9-0d0d318ffa30.jpeg)

In webtrees kann für eine verbundene Person nur "Zeuge" gewählt werden, was auch immer als Zeuge und nie als Zeugin angezeigt wird (keine geschlechtsspezifische Übersetzung vorgesehen).

**Comment by ric2016** [comment]
Es wurde die falsche Person zur Bestimmung der Übersetzung verwendet. Im Code gefixt.

**Comment by mpwt** [comment]
Thank you. It works.
