### ISSUE TITLE
Support _FSFTID

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_personal_facts#38]
See https://github.com/fisharebest/webtrees/issues/2829 .

This is NOT the AFN:
https://www.familysearch.org/search/family-trees/results?q.afnId=LR5C-WYH
doesn't find the individual from
https://www.familysearch.org/tree/person/details/LR5C-WYH
but this search does:
https://www.familysearch.org/tree/find/id?id=LR5C-WYH

We should also provide a sidebar replacing IndividualMetadataModule, so that we can show this fact in the sidebar.
(for that part note: which sidebar is initially expanded is hard-coded in individual-page.phtml, that's not great. Should be configurable per sidebar)

**Comment by ric2016** [comment]
Added in latest release.

**Comment by hartenthaler** [comment]
great! This helps to switch very fast to FamilySearch. I'm thinking about the same function to switch to Geni or wikitree the same way. Maybe using instead of _FSFTID already a custom version of the coming standard 7.0 EXID tag. Maybe:

```
1 _EXID Maximilian-Graf-von-Arco-auf-Valley/6000000012940999084
2 TYPE Geni
1 _EXID Ablett-3
2 TYPE wikitree
```

resulting in
```
https://www.geni.com/people/Maximilian-Graf-von-Arco-auf-Valley/6000000012940999084
https://www.wikitree.com/wiki/Ablett-3
```
What do you think?

**Comment by ric2016** [comment]
In general I agree that links to other global trees or resources should be possible as well.

I'm very hesitant to introduce new custom tags for this myself though. I'd rather leave this for webtrees itself (or others) to decide, maybe I'll reconsider in webtrees 2.1. (I'm also not optimistic that we'll see a widely used Gedcom 7.0 anytime soon by the way)

**Comment by hartenthaler** [comment]
I understand that you don't like to add a new custom tag. and maybe you are right that it will need some time to resolve the legal aspects of GEDCOM 7.0, so that we have to wait.

So I decided to misuse the existing tag _FSFTID a bit and add an additional TYPE to this tag:

```
1 _FSFTID Maximilian-Graf-von-Arco-auf-Valley/6000000012940999084
2 TYPE Geni
1 _FSFTID Ablett-3
2 TYPE wikitree
```

When I'm adding some code to your "FunctionsPrintFacts_2x.php" (quick and dirty) this does what I would like to have.

```
      case '_FSFTID':
        switch ($type) {
          case 'Geni':
            echo '<div class="field"><a href="https://www.geni.com/people/', $value, '">', e($value), '</a></div>';
            break;
          case 'wikitree':
            echo '<div class="field"><a href="https://www.wikitree.com/wiki/', rawurlencode($value), '">', e($value), '</a></div>';
            break;
          default:
            echo '<div class="field"><a href="https://www.familysearch.org/tree/person/details/', rawurlencode($value), '">', e($value), '</a></div>';
            break;
        }
```
For me, it would be ok to live with this modified _FSFTID tag until the GEDCOM standard 7.0 arrives and I can replace then _FSFTID by EXID.

It would be ok for me to replace your "FunctionsPrintFacts_2x.php" with an own (new) module instead of replacing code in your function; maybe you can add a hook to your code to make it easier or give me a hint, how I should code such a module.

**Comment by ric2016** [comment]
I expect all this to become much easier in webtrees 2.1. I also hope all the functionality of the Functions* classes will be modernized. 

With that in mind, the easiest option until then is probably to provide the modified FunctionsPrintFacts_2x.php via your own custom module, which doesn't have to do anything but load the modified FunctionsPrintFacts_2x.php earlier (e.g. directly in module.php) than the original FunctionsPrintFacts_2x.php gets loaded.

[See here for examples](https://github.com/vesta-webtrees-2-custom-modules/vesta_common/blob/43a64b78d811c74089c681b304ca694836984d00/autoload.php#L28) where I replace webtrees core classes in the same manner (once directly via 'require_once', and once via the class loader - not sure why the latter was necessary).

**Comment by hartenthaler** [comment]
Thank you. I just defined what I like to do with _FSFTID, see [fsftid](http://hartenthaler.net/webtrees_addendum/fsftid.html)

I have thousands of such external links, most of them are coded at the moment as "1 SOUR service / 2 PAGE http://xxx"
I will remove these Sources now and replace them with "1 _FSFTID id / 2 TYPE service" and as soon as Gedcom 7.0 is implemented with EXID (ok we will see when this happens).

Then I will modify your code to support all these external links and test this approach.

**Comment by hartenthaler** [comment]
I replaced your code in FunctionsPrintFacts_2x.php by

```
      case '_FSFTID':
        // external id in INDI record:
        // +1 _FSFTID <Special> {0:M}
        // +2 TYPE <Text> {0:1}
        // see definition at http://hartenthaler.net/webtrees_addendum/fsftid.html
        
        // tbd: array $exid should be under the control of webtrees admin and should be editable in the control panel
        // first column: service (<Text>)
        // second column: URL to be generated
        // tbd: maybe comments can be added as the third column
        // tbd: maybe upper/lower case doesn't matter in service names, so make everything lower case?
        
        // if table is empty => no function
        // first row is default if there is no "2 TYPE <Text>" (should be FamilySearch FamilyTree (FSFT))
        // all URLs have to contain %Special% which will be replaced by the external id (e.g. if there is "1 _FSFTID LJG2-3TJ" then %Special% will be replaced by "LJG2-3TJ")
        // special for wikipedia: URL has to contain %Language% (e.g. if there is "2 TYPE wikipedia - en" then %Language% will be replaced by "en"); two characters language codes are used
        // tbd: define more external services like: ancestry, Geneanet, Worldcat, Findmypast, WorldConnect, ...
        // html security functions have to be applied at the content of all entries in this table before "echo" them
        $exid = [
          "FSFT"            =>	"https://www.familysearch.org/tree/person/details/%Special%", // this is default if there is no "2 TYPE <Text>"
          "WikiTree"        =>	"https://www.wikitree.com/wiki/%Special%",
          "Geni"            =>	"https://www.geni.com/people/%Special%",                    // use name/number as external id
          "WeRelate"        =>	"https://www.werelate.org/wiki/Person:%Special%",
          "Roglo"           =>	"http://roglo.eu/roglo?%Special%",                          // use Roglo "permanent code" as exeternal id
          "geneee"          =>	"https://geneee.org/%Special%",
          "Find A Grave"    =>	"https://findagrave.com/memorial/%Special%",                // use number witout name as external id
          "wikidata"        =>	"https://www.wikidata.org/wiki/%Special%",
          "wikipedia"       =>	"https://%Language%.wikipedia.org/wiki/%Special%",          // %Language% will be replaced, too (use "wikipedia - xx" as service)
          "VIAF"            =>	"https://viaf.org/viaf/%Special%",
          "GND"             =>	"http://d-nb.info/gnd/%Special%",
          "Facebook"        =>	"https://www.facebook.com/%Special%",
          "XING"            =>	"https://www.xing.com/profile/%Special%/cv",
          "LinkedIn"        =>	"https://www.linkedin.com/in/%Special%",
          "Instagram"       =>	"https://www.instagram.com/%Special%",
        ];
        
        // do nothing if $exid is empty
        if (count($exid) >0) {
            
            // special case for empty $type and $type = "wikipedia - xx"; xx is two characters language code
            // valid: wikipedia, wikipedia-de, wikipedia - en, wikipediafr, ...
            // default is German wikipedia
            $special = "wikipedia";
            $language = "de";
            if ($type == "") {
                // if there is no "2 TYPE", then the first row of $exid is default
                $type = array_keys($exid)[0];
            } elseif (substr($type, 0, strlen($special)) == $special) {
                $language = substr(trim(strtr(substr($type, strlen($special)), '-', ' ')), 0, 2);
                $type = "wikipedia";
            }
            // if $type is an key in $exid then construct URL and echo result
            if (array_key_exists($type, $exid)) {
                $url = str_replace('%Language%', $language, str_replace('%Special%', $value, $exid[$type]));
                // tbd: should there be a function to show $url like rawurlencode(), e(), Filter::expandUrls() ???
                echo '<div class="field"><a href="', $url, '">', e($value), '</a></div>';
            } else {
                // tbd: how should the error be reported or should this error be ignored?
                echo '<div class="field">Service ', $type, ' is not defined by webtrees admin.</div>';
            }    
        }
```
and tested it using two persons in my tree:
- https://ahnen.hartenthaler.eu/tree/ahnen/individual/I30234/Amelie-Goler-von-Ravensburg-I30234
- https://ahnen.hartenthaler.eu/tree/ahnen/individual/I99/Franziska-Frenze-Baumgartner-I99 

I like this new possibility to have external links available. I will now add these _FSFTID tags and delete the old solutions in my family tree. Do you have any comments?

**Comment by ric2016** [comment]
You probably need further adjustments to make the Type editable.
By the way, I'll have to adapt to the changes of the latest webtrees release (tag is now displayed as "INDI:_FSFTID") - not sure how long that will take.

**Comment by hartenthaler** [comment]
Using 2.0.12 allows me now to see the edit buttons in the navigation bar. So it is very easy now to edit _FSFTID together with the TYPE. Perfect. And INDI:_FSFTID is better for me than the text before, that referenced FamilySearch only.
