### ISSUE TITLE
Display of Mapire-map - suggestion

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_personal_facts#4]
Perhaps it would be better to use a slightly different URL - remove the `/embed` from the link, and change the layers parameter to `layers=here-aerial%2C158`

The link produced now:
https://mapire.eu/en/map/europe-19century-secondsurvey/embed/?bbox=2085660.310250728%2C6270893.531117584%2C2148338.6734445724%2C6306818.934411616&map-list=0&layers=158

the new link:
https://mapire.eu/en/map/europe-19century-secondsurvey/?bbox=2085660.310250728%2C6270893.531117584%2C2148338.6734445724%2C6306818.934411616&map-list=0&layers=here-aerial%2C158

Ladislav

**Comment by ric2016** [comment]
I prefer the embedded mode - But I'll just add another configuration parameter for this.

I don't see how the 'here-aerial' parameter changes anything - What is the effect?

**Comment by ro-la** [comment]
I like the complete display - you cann easy switch to other map. I am mostly switching between the Second and Third Militar Survey.

The here-aerial parameter is adding a botom layer to the and so you can play with the "opacity" bar.
When its not added - no problem, but you have to select one of the "Base maps". Its helpful to display the todays situation.

Ladislav

**Comment by ric2016** [comment]
Fixed in the latest release.
