### ISSUE TITLE
Wrong gender of a godchild

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_personal_facts#46]
Displaying the associate person I have a wrong label for christening of a godchild - it states it is a God**son**, (wrong) and bellow is written **"niece"** (correct).

Using 2.0.15 and Vesta module 2.0.15.2.0.

I have no idea, if this is a new issue or an old one :-)

Ladislav
![obrázok_2021-04-19_090515](https://user-images.githubusercontent.com/60657963/115194882-5abe1780-a0ee-11eb-8ef5-fcfd2ab49715.png)

**Comment by ro-la** [comment]
It seems to be a problem when a godfather has a goddaugther or a godmother has a godson.

**Comment by ric2016** [comment]
Yes, the gender of the godparent is evaluated here, rather than the gender of the godchild. Will be fixed in the next release.

**Comment by ric2016** [comment]
Fixed in latest release.
