### ISSUE TITLE
Individual with Associate does not show translation

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_personal_facts#47]
Hallo, bitte schauen Sie mal in diese Problembeschreibung: https://github.com/fisharebest/webtrees/issues/3877. Ich glaube Ihr Add-on sollte diesbezüglich auch angepasst werden. Vielen Dank.

Dann kann ich das von mir beschriebene Problem unter https://github.com/fisharebest/webtrees/issues/3848 schließen.

**Comment by ric2016** [comment]
Fixed in 2.0.16.1.0.
