### ISSUE TITLE
Neues Ereignis/ Neue Tatsache kann nicht hinzugefügt werden

### ISSUE THREAD

**Issue by tobschn** [vesta-webtrees-2-custom-modules/vesta_personal_facts#49]
Webtrees Version: 2.0.16
System Info: Linux a2fb8 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64
PHP Version: 7.4.18

Ein neues Ereignis/ eine neue Tatsache kann nicht über den _Hinzufügen_-Button erstellt werden. Der Button hat bei mir keine Funktion.
Das Drop-Down Menü, genauso, wie die darunter liegenden Schnellverknüpfungen funktionieren.
Der von Webtress selbst bereitgestellte Ereignis/ Tatsachen - Tab funktioniert problemlos.

![image](https://user-images.githubusercontent.com/10728074/121001361-7f984800-c78b-11eb-9f52-ef6ef27104b3.png)

**Comment by ric2016** [comment]
Kann ich nicht nachvollziehen, funktioniert bei mir analog zum webtrees-Tab.
(Der Button hat nur nach Auswahl im Dropdown eine Funktion)

Gibt es Fehlermeldungen in der Konsole/ in den Developer Tools beim Anwählen des Buttons?

**Comment by tobschn** [comment]
So also ich habe nochmals etwas rumprobiert und folgende Fehlermeldung in der JS-Console feststellen können: `Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`
Diese tritt allerdings direkt auf, wenn die Seite geladen wird. Beim anwählen des Buttons wird keine Fehlermeldung angezeigt. Die Fehlermeldung hat aber wohl nichts mit deinen Erweiterungen zu tun, da dieser auch auftritt, wenn diese in der Webtrees-Verwaltung deaktiviert sind.

**Comment by tobschn** [comment]
Okay, hab noch eine weitere Fehlermeldung in den Webtrees logs gefunden. Sie wurde 3 mal hintereinander in den Logs gelistet. Sie ist wohl relativ direkt nach der Installation deiner Erweiterungen aufgetreten:

> SQLSTATE[42S01]: Base table or view already exists: 1050 Table &#039;ftree_gov_descriptions&#039; already exists (SQL: create table `ftree_gov_descriptions` (`type` int not null, `lang` varchar(8) not null, `description` varchar(128) not null, `from` mediumint null, `to` mediumint null) default character set utf8 collate &#039;utf8_unicode_ci&#039; engine = InnoDB) …/vendor/illuminate/database/Connection.php:664 #0 …/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;create table `f...&#039;, Array, Object(Closure)) #1 …/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run(&#039;create table `f...&#039;, Array, Object(Closure)) #2 …/vendor/illuminate/database/Schema/Blueprint.php(97): Illuminate\Database\Connection-&gt;statement(&#039;create table `f...&#039;) #3 …/vendor/illuminate/database/Schema/Builder.php(278): Illuminate\Database\Schema\Blueprint-&gt;build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar)) #4 …/vendor/illuminate/database/Schema/Builder.php(167): Illuminate\Database\Schema\Builder-&gt;build(Object(Illuminate\Database\Schema\Blueprint)) <b>#5 …/modules_v4/vesta_gov4webtrees/Schema/Migration0.php(76): Illuminate\Database\Schema\Builder-&gt;create(&#039;gov_description...&#039;, Object(Closure))</b> <b>#6 …/modules_v4/vesta_common/VestaModuleTrait.php(229): Cissee\Webtrees\Module\Gov4Webtrees\Schema\Migration0-&gt;upgrade()</b> <b>#7 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(94): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule-&gt;updateSchema(&#039;\\Cissee\\Webtree...&#039;, &#039;SCHEMA_VERSION&#039;, 2)</b> <b>#8 …/modules_v4/vesta_common/VestaModuleTrait.php(264): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule-&gt;onBoot()</b> #9 …/app/Services/ModuleService.php(866): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule-&gt;boot() #10 …/app/Http/Middleware/BootModules.php(60): Fisharebest\Webtrees\Services\ModuleService-&gt;bootModules(Object(Fisharebest\Webtrees\Module\ColorsTheme)) #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #15 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #16 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3) #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 …/app/Http/Middleware/BadBotBlocker.php(222): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 …/app/Http/Middleware/RegisterFactories.php(74): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #41 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #43 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #47 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #51 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #53 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #55 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #56 …/index.php(57): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest)) #57 {main}

**Comment by ric2016** [comment]
Die 1. Fehlermeldung ist etwas ganz anderes, die 2. hat mit diesem Problem auch nichts zu tun (kann vermutlich ignoriert werden, wenn sie nicht wiederholt auftaucht - ist mir aber auch nicht klar, wie das überhaupt passieren kann, da direkt vorher geprüft wird, ob die Tabelle existiert).

**Comment by ric2016** [comment]
Problem tritt auf, wenn beide Tabs (Stanadrd und Vesta) aktiviert sind.
Workaround: Nur eines von beiden verwenden.

Lösung (TBI): Separate view für Vesta-Tab (add-fact-row.phtml mit anderer id als #add-fact)

**Comment by ric2016** [comment]
Fixed in Release 2.0.16.2.0.
