### ISSUE TITLE
"add from clipboard" is not shown

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_personal_facts#5]
If you copy something to the clipboard normally there appears a line "Add from clipboard" at the bottom of all the facts directly above "Fact or event", but this doesn't happen in the vesta_personal_facts (webtrees 2.0.3).

**Comment by hartenthaler** [comment]
Thank you! Problem solved.

**Comment by ric2016** [comment]
(this is not released yet, therefore I'll keep the issue open until the next release)

**Comment by ric2016** [comment]
Fixed in latest release.
