### ISSUE TITLE
ADDR lines are displayed without line breaks

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_personal_facts#59]
It seems there is a problem in displaying address data in the Vesta Facts and events module.

```
2 ADDR Line1
3 CONT Line2
3 CONT Line3
```

is displayed as

`Address: Line1 Line2 Line3`

It works the same way also when the module "Classic look & feel" is disabled.

Setting for MarkDown has no effect to the display.

The display on the webtrees Facts and Events tab is OK.

Ladislav

**Comment by ric2016** [comment]
Thanks - Fixed now in Release 2.0.19.0.4. 

Hopefully these changes in webtrees core code (where this was handled differently in an earlier version) will be less problematic from 2.1 onwards.
