### ISSUE TITLE
Death of a child is not displayed in the parents Facts & Events Tab

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_personal_facts#60]
When displaying events of close relatives the death of a child is not displayed in the Vesta Facts & Events Tab. In the "normal" Facts & Events tab is this event displayed OK.
Death of grandchildren are displayed on both tabs OK.

Is this a bug, or do I have a misconfiguration somewhere?

Ladislav

**Comment by ric2016** [comment]
It's a bug, I missed a change in the original module. Will be fixed in the next Vesta release.

**Comment by ric2016** [comment]
Fixed in Release 2.0.19.1.0.
