### ISSUE TITLE
2.0.23 - Facts and Events - Error message 

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_personal_facts#64]
Call to undefined method Vesta\CommonI18N::associatedFactsAndEvents() …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended_20.php:242
#0 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_20.php(169): Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended_20->getToggleableFactsCategories('_BIRT_GCHI,_BIR...', true)
vesta-webtrees-2-custom-modules/vesta_classic_laf#1 …/app/Module/ModuleTabTrait.php(116): Cissee\WebtreesExt\Module\IndividualFactsTabModule_20->getTabContent(Object(Cissee\WebtreesExt\IndividualExt))
vesta-webtrees-2-custom-modules/vesta_classic_laf#2 …/app/Http/RequestHandlers/ModuleAction.php(88): Cissee\WebtreesExt\Module\IndividualFactsTabModule_20->getTabAction(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#3 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#5 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#7 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule_20.php(226): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule_20->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#9 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_personal_facts#12 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#16 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#18 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#20 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#21 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
vesta-webtrees-2-custom-modules/vesta_classic_laf#22 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
vesta-webtrees-2-custom-modules/vesta_places_and_pedigree_map#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#24 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#26 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#28 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#30 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#32 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#34 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#36 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#38 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#40 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#42 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#44 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#46 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#47 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#49 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#51 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#53 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#55 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#57 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
vesta-webtrees-2-custom-modules/vesta_classic_laf#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#60 …/app/Webtrees.php(241): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
vesta-webtrees-2-custom-modules/vesta_classic_laf#61 …/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
vesta-webtrees-2-custom-modules/vesta_classic_laf#62 …/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest()
vesta-webtrees-2-custom-modules/vesta_classic_laf#63 {main}

**Comment by ric2016** [comment]
Fixed in latest release 2.0.23+2.1.0-beta.2.0.1

**Comment by webtrees-pesz** [comment]
Thx Richard, for your fast support.

Best regards, Peter
