### ISSUE TITLE
Displaying wide tables

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_personal_facts#69]
It seems that the problem with displaying (on notebook/PC) wide tables (typical from a census transcript) was solved in version 2.1. beta 2. 

Using the Vesta Facts and events this corrrection dont work. 

![image](https://user-images.githubusercontent.com/60657963/163002865-0b39392a-488a-492f-908f-9d9979bd8e9f.png)

On the standard Facts&Event tab it looks this way:
![image](https://user-images.githubusercontent.com/60657963/163003199-93baeab7-9e5e-469a-b3a0-df9bafbc8188.png)

**Comment by ric2016** [comment]
Fixed in latest release ...2.0.
