### ISSUE TITLE
Extended 'Facts and Events' Tab

### ISSUE THREAD

**Issue by heiler** [vesta-webtrees-2-custom-modules/vesta_personal_facts#71]
"Associated Events" is displayed, although not selected in the settings.
A German translation is probably also missing.

![Screenshot 2022-04-17 at 10-48-41 Johanna Lauscher 1900–1990 – webtrees](https://user-images.githubusercontent.com/2920260/163707498-1ce79ae4-089d-4e52-a63d-08320e9a04b3.png)

**Comment by ric2016** [comment]
> although not selected in the settings

The respective setting has been removed in order to align with webtrees 2.1, which now has the same separate checkbox.
Translation should work in latest Vesta release (tested in 2.0 and 2.1 branch).
