### ISSUE TITLE
arcanum map: no available historic map leads to a white page

### ISSUE THREAD

**Issue by ungeahnt** [vesta-webtrees-2-custom-modules/vesta_personal_facts#74]
For certain regions (e.g. places in Bulgaria) arcanum has no map material and only a white page is displayed. 

This is a bit confusing at first sight, because you don't know if the page is still loading and you are waiting. Only when you zoom out of the map (multiple times), you see that there is a white spot.

Therefore my question is, if the 'arcanum API' offers a possibility to query the availability of map material. If no map is available, then it would be nice to display at least the map in a standard view (e.g. overall view of Europe) and/or display a message for the user.

... thanks a lot for the vesta moduls!

**Comment by ric2016** [comment]
I considered this a while ago.

There is a way to detect the available maps for specific coordinates (you can see this on the arcanum site itself when clicking on the 'More Maps' button): While there is no actual API spec, but investigating with browser development tools shows that requests such as <https://maps.arcanum.com/en/map/europe-19century-secondsurvey/list/?bbox=1022898.3218344878,6492628.116290913,1216436.8774525542,6522438.557322132> return the list of available maps, which could be used for this.

The main problem is that these requests would have to be executed whenever a map link is about to be displayed - even if isn't actually used - which is problematic
* for performance (we could cache those though)
* I'm not sure whether Arcanum would actually be ok with lots of queries of this kind, this goes beyond simply linking to one of their urls

Alternatively, the map link would have to adjusted in the onclick browser event, which could be confusing for the user (the map is shown as available, but actually isn't). The second point from above would still be an issue though.

After reaching this point in the analysis, I decided not to pursue this further ...

Maybe there are other ways to support this? E.g. refine the polygons used for the map boundary (currently a simple rectangle actually, defined statically [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_personal_facts/blob/583eb2fd45b7130741c3996c7c30222e52b81f34/FunctionsFactPlace.php#L142)).

**Comment by ungeahnt** [comment]
> The main problem is that these requests would have to be executed whenever a map link is about to be displayed - even if isn't actually used - which is problematic

Do I understand it correctly: you want to do the 'list query' already when calling a website with an arcanum-button (e.g. 'facts and events') and deactivate the button if no map is available? 
This would be very user-friendly of course, but I think for the above reasons it would be enough to do the query only when clicking.

>- which is problematic
    for performance (we could cache those though)
    I'm not sure whether Arcanum would actually be ok with lots of queries of this kind, this goes beyond simply linking to one of their urls

Such free offers should not be overstressed and the performance should not suffer either.

> Alternatively, the map link would have to adjusted in the onclick browser event, which could be confusing for the user (the map is shown as available, but actually isn't). The second point from above would still be an issue though.

I have no idea how a click is processed, but would it perhaps be possible to query the list with the click and if there is no map, 'simply' call up an overview map? 

Then the user can realize relatively quickly that there are no maps for his location.

Or do you think that querying the list already creates too much overhead?

**Comment by ric2016** [comment]
> Or do you think that querying the list already creates too much overhead?

That in itself would probably be ok, but:

> Then the user can realize relatively quickly that there are no maps for his location.

In this case the map link icon would show a different url in that case from what is actually called. This is at least confusing and in my opinion gives a rather shady impression: If a follow a link to an external site and end up somewhere else, I start to question the origin site's integrity.

Therefore I'm hesitant to support this.

**Comment by ungeahnt** [comment]
> If a follow a link to an external site and end up somewhere else, I start to question the origin site's integrity.

ok, I see this is not a good solution. I've also thought about to change the zoom factor by the software to 3 or 4 (without to change the URL), but that would also only be a semi-finished workaround.
The user would see something with this zoom factor, but would not know where his place is on the map and would probably search around until he realizes that there is no historical map for his place.

The problem with the complete white website also only occurs if the "Show linked map with additional options" checkbox is not selected in the settings. However, if this option is active, then at least a modern background map is displayed. But again, the user must first find out that there is no historical map. 

May you know a URL-string to set the background with the embedded version (without the 'additional options')?

To solve the problem properly, it would be necessary - as you suggested - to somehow check all links first and then show the arcanum-buttons or not ... but then we have the problems you mentioned in the beginning again (performance, number of server requests).

I will leave the "additional options" active for now and get along with it. If there is no objection, then I would close here.

**Comment by ric2016** [comment]
> To solve the problem properly, it would be necessary - as you suggested - to somehow check all links first

It seems that even this is not possible the way I described: The map is offered by Arcanum even for locations which it doesn't cover.

So there is no good solution for this, other than using the map with additional options in these case, as you describe.

Therefore closed for now.
