### ISSUE TITLE
Error in Webtrees 2.14

### ISSUE THREAD

**Issue by SnarfW** [vesta-webtrees-2-custom-modules/vesta_personal_facts#78]
FYI: I get the following error with the latest release of Webtrees (2.14):

Fatal error in module: vesta_personal_facts
TypeError: Fisharebest\Webtrees\Module\IndividualFactsTabModule::__construct(): Argument #1 ($clipboard_service) must be of type Fisharebest\Webtrees\Services\ClipboardService, Fisharebest\Webtrees\Services\ModuleService given...

**Comment by ric2016** [comment]
The Vesta modules are not compatible with 2.1.4 yet!

**Comment by heiler** [comment]
If vesta modules are inactivated, default modules must be activated. If this is not done, chaos will result. The solution to the problem can only be that the developers of Webtrees and the additional modules coordinate.

**Comment by ric2016** [comment]
> The solution to the problem can only be that the developers of Webtrees and the additional modules coordinate.

Coordinate their releases? That's not realistic.

I have attempted to address these issues by adding warnings to the upgrade wizard re: incompatible Vesta versions. These are ignored too often and anyway aren't visible when upgrading manually. 

So I'll enforce the version check in the future. I usually have compatible Vesta releases ready shortly after a webtrees update. If users decide to upgrade webtrees earlier than that, there's nothing more I can do about it.

**Comment by SnarfW** [comment]
> If users decide to upgrade webtrees earlier than that, there's nothing more I can do about it.

I agree on this, normally I do wait. This time I was too early.  
My message was only to inform you, not to complain or something like that.

**Comment by ric2016** [comment]
@[SnarfW](https://github.com/SnarfW) understood, it's just that this is a recurring issue. I'll address it differently in the future.

If webtrees would follow semantic versioning guidelines more closely, patch releases such as this one would actually be unproblematic.
