### ISSUE TITLE
Changes in webtrees-main

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_personal_facts#80]
Schauen Sie sich mal die Änderungen in https://github.com/fisharebest/webtrees/commit/154ba7474e3da56cb88a6422a92add708eb5394a an. Dies sollte auch in Ihrem Modul geändert werden. Vielen Dank.

**Comment by ric2016** [comment]
Ist angepaßt im aktuellen Vesta-Release 2.1.5.0.0
