### ISSUE TITLE
"Only show specific facts and events" doesn't appear to be working

### ISSUE THREAD

**Issue by JesseWebDotCom** [vesta-webtrees-2-custom-modules/vesta_personal_facts#83]
After ensuring I am displaying the vesta facts and event module (and hiding the native facts and events), have checked ""Only show specific facts and events" , have set only 2 event types in both drop downs (birth, marriage), saved and then refreshed the individual page, I do not see any difference - I still see all event types.

What I'm trying to do is hide events like "source citation" and "record id number".  I wish the module had a "hide these event types" option.

**Comment by ric2016** [comment]
This option refers to "Associated events" (see the left side of the option panel) and works for those.

If you want to hide specific facts and events, your best option are the tree- specific privacy settings.

There are no plans to make this configurable further in Vesta.

**Comment by JesseWebDotCom** [comment]
Thanks!
