### ISSUE TITLE
Feature Request: Profile photos of individuals

### ISSUE THREAD

**Issue by JesseWebDotCom** [vesta-webtrees-2-custom-modules/vesta_personal_facts#84]
I'd like to request an enhancement where the module shows individual profile photos, just like the how the Families tab shows them.

**Comment by ric2016** [comment]
I'm afraid don't understand the request - Where exactly should additional images be shown?

**Comment by JesseWebDotCom** [comment]
The module displays 2 columns, the label on the left (ex. birth of a son) and the content on the right (ex. John Doe). I would like the content on the right to display the individual's picture along with their name, like how its displayed here:
![](https://webtrees.net/assets/img/tree-mock-screen.png)

**Comment by JesseWebDotCom** [comment]
And like how they are displayed here:
![](https://www.ancestry.com/corporate/sites/default/files/wp_images//CSU_thumbnail.png)

**Comment by ric2016** [comment]
I don't think this would work well with how facts and events are displayed in general.
You second screenshot implies that you're actually looking for a different way altogether to display facts and events (something like a "timeline" tab).

In any case, this should perhaps be discussed for webtrees itself. I do not plan to support this in Vesta specifically.

**Comment by JesseWebDotCom** [comment]
I was able to get this working in a custom theme. I'm gonna try to edit/add this to my locally installed vesta module next.

The huge benefit to having the images in the table is 1) the emotional value (seeing the pictures of loved ones) and 2) reduces boredom (seeing graphics/photos vs just plain text).

if you care, i can share my code once I'm done.

**Comment by ric2016** [comment]
I'm sorry I kept this open for so long without a reply.

Anyway I'm glad you could figure out how to add this feature locally. I'm closing this issue as this won't be implemented in Vesta.
